MaeumGaGym/MaeumGaGym_Backend

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoDuplicateCheckUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/KakaoSignupUseCase.kt
=> 🔀 :: 카카오 포트 추가

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/exception/UserNotFoundException.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoLoginService.kt
=> 🔀 :: 로그인 Port 구현

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/out/ExistUserByOAuthIdPort.kt
=> 🔀 :: ExistsUserByOAuthId

maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/AppleAuthAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/GeneratePublicKeyAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/GoogleAuthAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/KakaoAuthAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/auth/adapter/ReadCurrentUserAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt, maeumgagym-presentation/build.gradle.kts, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/AppleAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/AuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/GoogleOAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/KakaoAuthController.kt
=> ♻ :: 책임에 맞지 않는 어노테이션 수정

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/mapper/PoseMapper.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadByIdUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/FindPoseByIdPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/pose/controller/PoseController.kt
=> 🔀 :: pose의 id를 Long으로 수정

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/AuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/GoogleOAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/auth/controller/KakaoAuthController.kt
=> 🔀 :: Google 로그인 오류 수정

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseLongIdEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseLongIdTimeEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseTimeEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseUUIDTimeEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routin/entity/RoutineJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt
=> 🔀 :: BaseEntity 분리

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/TableNames.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/converter/StringAttributeConverter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/converter/PickleTagConverter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleCommentJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleLikeJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleReplyJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleLikeRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt
=> 🔀 :: 피클 엔티티 설계

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/mapper/RoutineMapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/ReadCurrentUserAdapter.kt
=> 🔀 :: Routine Entity 수정

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/ExerciseInfoDto.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/RoutineStatusDto.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineListResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadAllMyRoutineUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadAllRoutineByUserIdPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadAllMyAllMyRoutineService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/dto/response/UserResponse.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/routine/controller/RoutineController.kt
=> 🔀 :: 내 루틴 조회 API

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/FeignDeletePicklePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/FileClient.kt
=> 🔀 :: 피클 삭제 기능 구현

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/entity/PickleLikeJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/mapper/PickleMapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/request/PickleUploadRequest.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/Pickle.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/GenerateUploadURLPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/LoadPickleService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UpdatePickleService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadPickleService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/file/FileAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/feign/file/FileClient.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/env/file/FileProperty.kt, maeumgagym-infrastructure/src/main/resources/application.yml, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/request/PickleUploadWebRequest.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/dto/response/PickleWebResponse.kt
=> 🌟 :: PK 수정

buildSrc/src/main/kotlin/Dependencies.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt, maeumgagym-infrastructure/build.gradle.kts, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/swagger/SwaggerConfig.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/security/SecurityConfig.kt, maeumgagym-infrastructure/src/main/resources/application.yml, maeumgagym-presentation/build.gradle.kts, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AppleAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/GoogleOAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/KakaoAuthController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
=> 🔀 :: Swagger 설정

build.gradle.kts, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt, maeumgagym-infrastructure/build.gradle.kts, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/QuoteTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/exception/MismatchQuoteAndQuoterException.kt
=> 🔀 :: Quote 테스트 코드 추가

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/entity/RoutineJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/DeleteRoutineUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutineByIdPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTests.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/RoutineWebResponse.kt
=> 🔀 :: 루틴 PK 타입 Long으로 변경

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/request/UpdateRoutineRequest.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/UpdateRoutineUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/DeleteRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/UpdateRoutineServiceTests.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/request/CreateRoutineWebRequest.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/request/UpdateRoutineWebRequest.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebListResponse.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/response/RoutineWebResponse.kt
=> 🔀 :: 루틴 수정 API

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/exception/ExerciseListCannotEmptyException.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt
=> 🌟 :: 예외 추가

maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/AuthTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/junit5/DuplicatedCheckServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/junit5/JwtTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/junit5/QuoteTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/junit5/CreateRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/junit5/DeleteRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/junit5/ReadRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/junit5/UpdateRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/module/RoutineTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/junit5/ReadCurrentUserAdapterTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/junit5/WithdrawalUserServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/module/UserTestModule.kt
- Auth와 관련된 UseCase 중 누락된 테스트가 존재하는지 확인해주세요.
- 누락된 실패 상황이 존재하는지 중점적으로 확인해주세요.
- 테스트 코드에 잘못된 로직이 존재하는지 확인해주세요.
=> 🔀 :: Auth 테스트 코드 추가

.github/workflows/release-auto.yml
=> ✨ :: Release Auto Create

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseUUIDEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/base/BaseUUIDTimeEntity.kt
=> 🔀 :: UUID 4로 변경

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/entity/WakaTimeJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/wakatime/mapper/WakaTimeMapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/model/WakaTime.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
• JPA entity의 life cycle에서 이벤트를 발생 시켜 isNew를 위해 select query가 나가는 것을 방지
=> ⚡️ :: update or insert 쿼리 성능

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PicklePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/UserPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/repository/UserRepository.kt
• exists(count(*)) query -> find(select *) query
• native로 작동하는 select query, limt option 추가
=> ⚡️ :: exists, native query 

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleReplyListResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/dto/response/PickleReplyResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/model/PickleReply.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/LoadAllPickleReplyUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllReplyByParentCommentPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPickleReplyService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
- 피클 대댓글 조회 기능을 추가하였습니다.
- Controller 부분에서 pathvariable 한개로만 받으면 댓글 조회랑 path가 겹쳐서 /reply 를 추가하였습니다.
=> ✨ :: 피클 대댓글 조회 기능 추가

buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/DependencyVersions.kt, maeumgagym-infrastructure/build.gradle.kts, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/DuplicatedCheckServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/auth/JwtTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/QuoteServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/quote/exception/MismatchQuoteAndQuoterException.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/CreateRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/DeleteRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/ReadRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/UpdateRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/ReadCurrentUserAdapterTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/UserTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/WithdrawalUserServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/WakatimeTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/WakatimeTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/exception/ErrorTooBigException.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/exception/WakatimeDoesNotSavedException.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/error/MaeumGaGymTestException.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/error/TestErrorCode.kt
- TestModule 필드 private 처리
- Kotest Dependence 제거
- internal 처리된 @see 참조 수정
- 안 쓰이는 메소드 삭제
=> 📝 :: 테스트 클래스 정리

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/ReadAllPagedPickleCommentUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/ReadAllPickleCommentsUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllPagedPickleCommentsByVideoIdPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadAllPickleCommentsByVideoIdPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPagedPickleCommentService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionHandler.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
- JPA에서 제공하는 Pagable을 통해 Paging 처리를 하였습니다
=> ✨ :: 댓글 조회 Paging 처리

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleCommentPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleCommentRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleCommentUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/DeletePickleCommentPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/ReadPickleCommentPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/CreatePickleReplyCommentService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleCommentService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/ReadAllPickleReplyService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt
=> ✨ :: 피클 댓글 삭제 기능

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/PickleReplyPersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pickle/repository/PickleReplyRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/CreatePickleUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleCommentUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleReplyUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/DeletePickleUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/in/PickleDeleteUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/port/out/DeletePickleReplyPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleCommentService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleReplyService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/DeletePickleService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pickle/service/UploadCreatePickleService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleCommentController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pickle/PickleReplyController.kt
=> ✨ :: 피클 대댓글 삭제 기능

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stag.yml
- develop 에 푸쉬 시 stag에 배포, main에 푸쉬 시 prod에 배포하도록 설정하였습니다.
=> ✨ :: Deploy Workflow 추가

maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/filter/FilterConfig.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAccessDeniedHandler.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAuthenticationEntryPoint.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionFilter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/GlobalExceptionHandler.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/public/PublicController.kt
- CSRF Token 발급 용 API 생성
ㄴ LB 헬스 체크용으로도 사용가능
- CSRF Token Missing일 시 message 반환 하도록 변경
- token이 require된 API에 token이 없을 시 403반환 -> 401 및 message 반환
=> ✨ :: CSRF Token 발급용 API

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/error/CustomAuthenticationEntryPoint.kt, maeumgagym-infrastructure/src/main/resources/application.yml, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
=> ✨ :: health check API

maeumgagym-infrastructure/src/main/resources/application-prod-datasource.yml, maeumgagym-infrastructure/src/main/resources/application-stag-datasource.yml, maeumgagym-infrastructure/src/main/resources/application.yml
=> 🚀 :: 1.2.1 PROD

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stag.yml, maeumgagym-infrastructure/src/main/resources/application.yml
=> 🚀 :: 1.2.2 PROD

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineNativeRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/RoutineRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/exception/OtherRoutineAlreadyUsingAtDayOfWeekException.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutinePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/DeleteRoutineService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/UpdateRoutineService.kt, maeumgagym-infrastructure/build.gradle.kts, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/CreateRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/UpdateRoutineServiceTests.kt
- 요일마다 하나의 루틴만이 수정될 수 있도록 검증하는 로직 추가
- 관련 테스트 코드 작성
=> 📝  :: 루틴이 요일당 하나만 할당되도록 수정

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/dto/response/RoutineResponseWrapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadTodayRoutineUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadTodayRoutineService.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/ReadRoutineServiceTests.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/routine/RoutineTestModule.kt
=> 📝:: 오늘의 루틴 조회 기능 구현

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/LocalDateConvertor.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/exception/ErrorCode.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/dto/request/UpdatePurposeRequest.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/exception/PurposeNotFoundException.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/UpdatePurposeUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/ReadPurposePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/service/UpdatePurposeService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/dto/UpdatePurposeWebRequest.kt
- 목표 수정 API 구현
- LocalDateConvertor 버그 수정
=> 📝 :: 목표 수정 API 구현

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/mapper/UserMapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/User.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt
- User 에 전체 와카타임 시간을 저장합니다.
- WakaTimeEnd 로직에서 second를 추가합니다.
=> ✨ :: 와카타임 전체시간 저장

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/in/LogOutUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/port/out/DeleteRefreshTokenPort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/LogOutService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/jwt/JwtAdapter.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/auth/AuthController.kt
- 로그아웃 API 를 구현하였습니다
- Refreshtoken을 삭제합니다.
=> ✨ :: 로그아웃 API 구현

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/dto/response/UserProfileResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/in/ReadUserUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/service/ReadUserService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/util/WakatimeUtils.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/statistics/PublicController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/UserController.kt
- util class가 잘 작동하는지 확인 해주세요
- nickname으로 검색되게 한 이유 : UserResponse에서 nickname을 주어서
=> ✨ :: 프로필 보기 API

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/Gender.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/PhysicalInfo.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/entity/UserJpaEntity.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/user/mapper/UserMapper.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/AppleOAuthService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/GoogleOAuthService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/auth/service/KakaoOAuthService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/dto/request/UpdateUserInfoRequest.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/GenderModel.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/PhysicalInfoModel.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/model/User.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/port/in/UpdateUserInfoUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/user/service/UpdateUserInfoService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/EndWakatimeService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/wakatime/service/StartWakatimeService.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/adapter/auth/RecoveryAdapter.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/scheduler/WakaTimeScheduler.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/user/UserTestModule.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/wakatime/WakatimeTestModule.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/UserController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/user/dto/UpdateUserInfoWebRequest.kt
=> ✨ 내 정보 변경 api 개발

maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/global/config/security/SecurityConfig.kt
=> 📝 :: CSRF Temporary disuse

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/dto/response/StepCountResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/in/CreateStepUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/in/ReadTodayStepCountUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/port/in/UpdateStepUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/step/service/ReadTodayStepCountService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/step/StepController.kt
- 오늘의 걸음 수 조회 API를 추가했습니다.
- 추가적으로 문서화를 진행했습니다.
=> 📝 :: 오늘 걸음 수 조회 API 추가

.github/workflows/comment-on-task.yaml
=> Asana Github sync

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/entity/PoseJpaEntity.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseDetailResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt, maeumgagym-infrastructure/src/test/kotlin/com/info/maeumgagym/domain/pose/PoseTestModule.kt
- 자세 Entity를 디자인에 맞게 다시 설계했습니다.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206792027604423
=> 📝 :: 자세 Entity 재설계

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseNativeRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseInfoResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseListResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseFromIdUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPoseFromTagUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/ReadPosePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseFromIdService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPoseFromTagService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
- 자세를 태그(간단한 이름, 자세한 이름, 간단한 자극 부위들, 자세한 자극 부위들)을 기반으로 자세를 찾을 수 있는 기능 추가
=> 📝 :: 자세 태그 기반 검색 

.github/workflows/discord-notification.yml
/kind 기능
/kind 문서
/kind 리펙토링
discordNotification workflow에 새로운 gif들을 추가했습니다.
```docs
```
=> PR :: discord notification yml Enchant

maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChain.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/error/filter/filterchain/ExceptionChainedFilterChainProxy.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/chained/ChainedFilterChain.kt, maeumgagym-infrastructure/src/main/kotlin/com/info/maeumgagym/filter/global/GlobalFilterChain.kt
/kind 리펙토링
/kind 버그
FilterChain 관련 클래스에 대해 리펙토링 및 ThreadLocal의 잘못된 사용의 수정을 진행했습니다.
```docs
```
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206917143120882
=> PR :: FilterChain 리펙토링

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/PosePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/pose/repository/PoseNativeRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/dto/response/PoseRecommendationListResponse.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/model/Pose.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/in/ReadPosesRecommendationUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/port/out/ReadPosePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/pose/service/ReadPosesRecommendationService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/pose/PoseController.kt
/kind 기능
자세 추천 조회 기능을 추가했습니다.
태그 기반 검색의 URI를 수정했습니다.
자세의 추천 조회 기능은 ORDER BY RAND(), LIMIT 10을 통해 구현했습니다.
```docs
```
=> PR :: 자세 추천 기능 추가

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/model/Routine.kt
/kind 리펙토링
- 월, 화, 수, 목, 금, 토, 일 순으로 정렬
- 월요일 -> 월 로 변경
```docs
```
=> PR :: Refact day_of_weeks

maeumgagym-core/src/main/kotlin/com/info/maeumgagym/common/convertor/DayOfWeekConvertor.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/CreateRoutineService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/CreateRoutineWebRequest.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/dto/UpdateRoutineWebRequest.kt
/kind 기능
/kind 버그
- 요일 입력 시 "요일" 단위 생략 가능하도록 수정
- Routine 생성 시, 존재하지 않는 Pose Id를 사용했을 때 PoseNotFound 예외가 발생하지 않는 오류 수정
```docs
이전에 DayOfWeekConvertor를 생성할 때, PR Review 과정을 생략했기 때문에 모르실 것이라 추측됩니다. 해당 모듈이 뭘 하는 지만 확인해주세요.
```
=> PR ::요일 입력 시 "요일" 단위 생략 가능하도록 수정

maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/PurposePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/purpose/repository/PurposeRepository.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/RoutinePersistenceAdapter.kt, maeumgagym-application/src/main/kotlin/com/info/maeumgagym/domain/routine/repository/current/RoutineRepository.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/in/ReadAllMyPurposeUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/purpose/port/out/ReadPurposePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/in/ReadAllMyRoutineUseCase.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/port/out/ReadRoutinePort.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadAllMyPurposeService.kt, maeumgagym-core/src/main/kotlin/com/info/maeumgagym/routine/service/ReadMyAllRoutineService.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/purpose/PurposeController.kt, maeumgagym-presentation/src/main/kotlin/com/info/maeumgagym/controller/routine/RoutineController.kt
/kind 기능
/kind 리펙토링
- 내 목표 조회 API를 구현했습니다.
- 내 루틴 조회 API를 Pagenation으로 수정했습니다.
```docs
전체 조회 -> Paged 조회로 수정되었기 때문에, API Path가 수정되었습니다.(me/all -> my)
```
=> PR :: 내 목표 조회 API 구현

src/main/kotlin/com/info/maeumgagym/infrastructure/config/interceptor/InterceptorChainConfig.kt, src/main/kotlin/com/info/maeumgagym/infrastructure/request/context/RequestContext.kt, src/main/kotlin/com/info/maeumgagym/infrastructure/request/context/RequestContextImpl.kt, src/main/kotlin/com/info/maeumgagym/infrastructure/request/interceptor/RequestContextInterceptor.kt
/kind 기능
현재 요청에 대한 HttpServletRequest 객체를 전역화하는 클래스를 추가했습니다.
```docs
```
=> PR :: Request 객체 전역화
